name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - pip install -r requirements.txt && pip install pytest
      - cat ${{ secrets.ENV }} | base64 -d > .env
      - pytest
      - rm .env